### ISSUE TITLE
Bean class org.example.domain.Customer is not enhanced?

### ISSUE THREAD

**Issue by Jingle-seven** [ebean-orm-examples/example-minimal#4]
when I run the junit test `CustomerTest` in IDEA ,I got
<pre>11:34:08.309 [main] ERROR i.e.s.deploy.BeanDescriptorManager - Error in deployment
java.lang.IllegalStateException: Bean class org.example.domain.Customer is not enhanced?
	at io.ebeaninternal.server.deploy.BeanDescriptorManager.setEntityBeanClass(BeanDescriptorManager.java:1521)</pre>

what that means?

**Comment by JFCote** [comment]
Same thing for me. When I install the Ebean Enhancement plugin and Ebean 10.x Enhancement plugin and activate them, it doesn't work either (another error, see below)...

Ebean is a very very hard library to get running with... 

@rbygrave Any ideas what could be wrong?

When I activate the Ebean Enhancement plugin, I receive a new error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/avaje/ebean/bean/EntityBean
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at Main.main(Main.java:6)
```

**Comment by JFCote** [comment]
@Jingle-seven I was able to fix it by installing the good version of the Ebean Enhancement plugin. For this example, you need the Ebean Enhancement 11 to make it work. Hope it helps!

**Comment by Jingle-seven** [comment]
@JFCote oh thanks, it worked 👍 , and the other way to run it is using maven: `mvn test`
